In [31]:
from datasets import load_dataset

import pandas as pd

In [9]:
df.columns

Index(['group_id', 'message_id', 'message_type', 'origin', 'original_text',
       'clean_text', 'annotation_type', 'annotation_target',
       'annotation_additional', 'team_performance', 'performance_change',
       'sol_tracker_message', 'sol_tracker_all'],
      dtype='object')

In [41]:
ds = load_dataset("gkaradzhov/DeliData")
df = ds["train"].to_pandas()
df = df[df["message_type"]=="MESSAGE"]
df["annotation_type"] = df["annotation_type"].fillna("None").apply(lambda x: x.replace("-"," ").replace("deliberation","").strip())
df["annotation_target"] = df["annotation_target"].fillna("0").apply(lambda x: x.replace("0",""))
df["acts"]  = df.apply(lambda x: x["annotation_type"] + (" - "+x["annotation_target"]) if x["annotation_target"]!="" else "",axis=1)
df["acts"] = df["acts"].apply(lambda x: x if x!="" else "None")
df["acts"].value_counts()

acts
Non probing - Reasoning    3919
None                       3275
Non probing - Solution     2913
Non probing - Agree        2047
Probing - Moderation        785
Probing - Solution          490
Probing - Reasoning         463
Non probing - Disagree      111
Name: count, dtype: int64

In [38]:
ds = load_dataset("gkaradzhov/DeliData")
df = ds["train"].to_pandas()
df = df[df["message_type"]=="MESSAGE"]
df["annotation_type"] = df["annotation_type"].fillna("None").apply(lambda x: x.replace("-"," ").replace("deliberation","").strip())
df["annotation_target"] = df["annotation_target"].fillna("0").apply(lambda x: x.replace("0",""))
df["acts"]  = df.apply(lambda x: x["annotation_type"] + (" - "+x["annotation_target"]) if x["annotation_target"]!="" else "",axis=1)
df["acts"] = df["acts"].apply(lambda x: x if x!="" else "None")
data = []
for ind,grp in df.groupby("group_id"):
    data.append({
        "speakers": grp["origin"].tolist(),
        "turns":grp["original_text"].tolist(),
        "dialogic_acts":grp["acts"].tolist(),
        "edu_level":"university"
    })
pd.DataFrame(data)

,speakers,turns,dialogic_acts,edu_level
0,"[Cat, Kiwi, Dolphin, Kiwi, Cat, Cat, Dolphin, ...","[Hello, hi, Hello, hw r u, I think we need to ...","[None, None, None, None, Non probing - Solutio...",university
1,"[Chipmunk, Unicorn, Bat, Cat, Bat, Chipmunk, B...","[one guess looks as good as any for now, Since...","[None, Non probing - Reasoning, Non probing - ...",university
2,"[Kiwi, Kiwi, Beaver, Lion, Beaver, Beaver, Kiw...",[the obvious answer would be to chhose A and 6...,"[Non probing - Solution, Probing - Moderation,...",university
3,"[Hamster, Kiwi, Bat, Kiwi, Falcon, Falcon, Bat...","[Hello, Hello!, hi, Which cards do you think w...","[None, None, None, Probing - Moderation, Non p...",university
4,"[Cat, Kiwi, Cat, Bee, Kiwi, Kiwi, Cat, Cat, Ki...","[i think its 5 and e, 'I also think it''s 5 an...","[Non probing - Solution, Non probing - Solutio...",university
...,...,...,...,...
495,"[Hamster, Lion, Alpaca, Alpaca, Lion, Hamster,...","[Hi, does anyone really understand the task?, ...","[Probing - Solution, None, Non probing - Solut...",university
496,"[Lion, Falcon, Butterfly, Giraffe, Falcon, Lio...","[hi, hi, Hello, Hi what did everyone submit?, ...","[None, None, None, Probing - Moderation, Non p...",university
497,"[Falcon, Falcon, Koala, Falcon, Falcon, Unicor...",[well you flip E to see if it has an even numb...,"[Non probing - Solution, Non probing - Solutio...",university
498,"[Leopard, Zebra, Zebra, Leopard, Zebra, Zebra,...","[Hi everybody, 'I selected 4 and A because the...","[None, Non probing - Reasoning, Non probing - ...",university
499,"[Falcon, Bat, Tiger, Alpaca, Tiger, Falcon, Ba...","[Hello, Hi, Hi, I chose the A because of the v...","[None, None, None, Non probing - Solution, Non...",university

In [42]:
pd.read_csv("/home/mortadha/Pilot/Benchmark/data/processed_datasets.csv")

,speakers,turns,dialogic_acts,edu_level,learning_context,comm_modality,agent_config,subject,language,dataset,extra
0,"['teacher', 'student', 'teacher', 'student', '...","['Okay. Math should be out. Everything else,...","[['None'], ['None'], ['None'], ['None'], ['Non...",elementary,classroom,in-person,Human-Human,maths,english,ncte,NaN
1,"['teacher', 'student', 'teacher', 'student', '...","['Red. It’s red, okay. Okay. Boys and girls...","[['None'], ['None'], ['None'], ['None'], ['Non...",elementary,classroom,in-person,Human-Human,maths,english,ncte,NaN
2,"['teacher', 'student', 'teacher', 'student', '...",['Okay. This afternoon we’re going to be doin...,"[['None'], ['None'], ['None'], ['None'], ['Non...",elementary,classroom,in-person,Human-Human,maths,english,ncte,NaN
3,"['teacher', 'multiple students', 'teacher', 's...","['Okay. Okay, good afternoon boys and girls.'...","[['None'], ['None'], ['None'], ['None'], ['Non...",elementary,classroom,in-person,Human-Human,maths,english,ncte,NaN
4,"['teacher', 'student', 'teacher', 'student', '...",['Perfect. Raise your what? I put your bag o...,"[['None'], ['None'], ['None'], ['None'], ['Non...",elementary,classroom,in-person,Human-Human,maths,english,ncte,NaN
...,...,...,...,...,...,...,...,...,...,...,...
7817,"['Hamster', 'Lion', 'Alpaca', 'Alpaca', 'Lion'...","['Hi, does anyone really understand the task?'...","['Probing - Solution', 'None', 'Non probing - ...",university,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7818,"['Lion', 'Falcon', 'Butterfly', 'Giraffe', 'Fa...","['hi', 'hi', 'Hello', 'Hi what did everyone su...","['None', 'None', 'None', 'Probing - Moderation...",university,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7819,"['Falcon', 'Falcon', 'Koala', 'Falcon', 'Falco...",['well you flip E to see if it has an even num...,"['Non probing - Solution', 'Non probing - Solu...",university,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7820,"['Leopard', 'Zebra', 'Zebra', 'Leopard', 'Zebr...","['Hi everybody', ""'I selected 4 and A because ...","['None', 'Non probing - Reasoning', 'Non probi...",university,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7821,"['Falcon', 'Bat', 'Tiger', 'Alpaca', 'Tiger', ...","['Hello', 'Hi', 'Hi', 'I chose the A because o...","['None', 'None', 'None', 'Non probing - Soluti...",university,NaN,NaN,NaN,NaN,NaN,NaN,NaN